# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 42-coin
email: 42-coin@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
 42 - the answer to life, the universe, and everything...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://42-coin.github.io" # the base hostname & protocol for your site
twitter_username: 42newchain
github_username:  42-coin

# Build settings
markdown: kramdown